export default function Glossary() {
  return (
    <div className="max-w-4xl space-y-10">
      <div>
        <h2 className="text-2xl font-semibold text-slate-900 mb-1">Glossary</h2>
        <p className="text-slate-600">
          Data definitions, calculation methods, and how to use each view in Health Insights.
        </p>
      </div>

      {/* DATA */}
      <section className="space-y-4">
        <h3 className="text-lg font-semibold text-slate-800 border-b border-slate-200 pb-2">Data</h3>
        <p className="text-slate-600 text-sm">
          All data is <strong>synthetic</strong> and generated by <code className="bg-slate-100 px-1 rounded">npm run generate-data</code>.
          No PHI or real identifiers. Written to <code className="bg-slate-100 px-1 rounded">data/</code>.
        </p>

        <div>
          <h4 className="text-sm font-medium text-slate-700 mt-4 mb-2">members.json (~10K records)</h4>
          <ul className="text-sm text-slate-600 space-y-1 list-disc list-inside">
            <li><strong>member_id</strong> — Unique identifier</li>
            <li><strong>age</strong>, <strong>gender</strong> — Used for demographic RAF</li>
            <li><strong>state</strong> — Geographic filter (e.g. TX, CA)</li>
            <li><strong>plan_type</strong> — Bronze, Silver, or Gold</li>
            <li><strong>risk_score</strong> — 0–1; used for utilization/risk segmentation</li>
            <li><strong>chronic_condition_flag</strong> — Boolean; used in suspect HCC rules</li>
            <li><strong>hcc_codes</strong> — Array of coded HCCs (e.g. HCC_18, HCC_85)</li>
            <li><strong>member_months</strong> — Enrollment months (default 12) for risk revenue</li>
          </ul>
        </div>

        <div>
          <h4 className="text-sm font-medium text-slate-700 mt-4 mb-2">claims.json (~100K records)</h4>
          <ul className="text-sm text-slate-600 space-y-1 list-disc list-inside">
            <li><strong>claim_id</strong>, <strong>member_id</strong> — Link to member</li>
            <li><strong>service_date</strong> — Date of service (for trends and recency)</li>
            <li><strong>claim_type</strong> — IP (inpatient), OP (outpatient), or RX (pharmacy)</li>
            <li><strong>allowed_amount</strong> — Cost used in MLR and PMPM</li>
          </ul>
        </div>
      </section>

      {/* CALCULATIONS */}
      <section className="space-y-4">
        <h3 className="text-lg font-semibold text-slate-800 border-b border-slate-200 pb-2">Calculations</h3>

        <div className="space-y-3 text-sm">
          <GlossTerm term="RAF (Risk Adjustment Factor)" id="raf">
            Demographic factor + sum of HCC weights for coded conditions, normalized to [0.3, 3.0].
            Formula: <code className="bg-slate-100 px-1 rounded">RAF = demographic_RAF + Σ(HCC_weights)</code>.
            Higher RAF → more risk adjustment revenue and different MLR interpretation.
          </GlossTerm>

          <GlossTerm term="Demographic RAF" id="demo-raf">
            Lookup by age band (18–34, 35–44, 45–54, 55–64, 65+) and gender. Illustrative values only; real CMS uses finer tables.
          </GlossTerm>

          <GlossTerm term="HCC weights" id="hcc-weights">
            Fixed weights per condition (demo only): Diabetes 0.32, CHF 0.45, COPD 0.29, CKD 0.38, Hypertension 0.14.
            Used in RAF and in “suspect” uplift estimates.
          </GlossTerm>

          <GlossTerm term="Suspect HCCs" id="suspect-hcc">
            Conditions <em>suspected but not coded</em>, inferred from claims patterns (e.g. high RX spend without Diabetes HCC).
            Rules require at least 2 signals where applicable. Used to estimate RAF leakage and revenue at risk; not diagnostic.
          </GlossTerm>

          <GlossTerm term="Risk adjustment revenue" id="risk-rev">
            <code className="bg-slate-100 px-1 rounded">RAF × $900 PMPM × member_months</code>. Base rate $900 PMPM is configurable in <code className="bg-slate-100 px-1 rounded">risk-adjustment.js</code>.
          </GlossTerm>

          <GlossTerm term="Raw MLR" id="raw-mlr">
            Medical Loss Ratio: <code className="bg-slate-100 px-1 rounded">total_allowed_claims / total_premium</code>.
            Premium is members × $15,000 (simplified annual).
          </GlossTerm>

          <GlossTerm term="Risk-adjusted MLR" id="adj-mlr">
            <code className="bg-slate-100 px-1 rounded">total_allowed_claims / (total_premium + risk_adjustment_revenue)</code>.
            Incorporates risk revenue so MLR is comparable across populations with different risk.
          </GlossTerm>

          <GlossTerm term="MLR improvement (bps)" id="bps">
            Basis points: <code className="bg-slate-100 px-1 rounded">(risk_adjusted_MLR − raw_MLR) × 10,000</code>.
            Negative means adjusted MLR is lower (better) when risk revenue is included.
          </GlossTerm>

          <GlossTerm term="PMPM" id="pmpm">
            Per Member Per Month: total allowed amount / (member count × months). Used in claims analytics.
          </GlossTerm>
        </div>
      </section>

      {/* VIEWS */}
      <section className="space-y-4">
        <h3 className="text-lg font-semibold text-slate-800 border-b border-slate-200 pb-2">How to use each view</h3>

        <div className="space-y-4 text-sm">
          <ViewCard title="Dashboard" viewId="dashboard">
            <p className="text-slate-600 mb-2">
              High-level KPIs and risk adjustment summary for the whole book of business.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>Use for: executive summary, trend checks, plan/state mix</li>
              <li>Core KPIs: total members, active claims (90d), raw MLR, high-risk %, avg cost per member</li>
              <li>Risk KPIs: avg RAF, % high RAF, risk adj. revenue, suspect RAF uplift, risk-adjusted MLR, agent-derived totals</li>
              <li>Charts: claims over time, cost by plan type, risk distribution, RAF by plan/state, executive risk leakage by state</li>
            </ul>
          </ViewCard>

          <ViewCard title="Member Explorer" viewId="members">
            <p className="text-slate-600 mb-2">
              Filter and drill into individual members; see RAF breakdown, HCC list, and suspected conditions.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>Use for: finding high-risk or high-RAF members, auditing suspect HCCs at member level</li>
              <li>Filters: state, plan type, risk score range, chronic condition flag</li>
              <li>Member profile: demographics, recent claims, RAF (demographic + HCC), HCC list with weights, suspected HCCs with reasons, risk adj. revenue, agent/orchestrator output</li>
            </ul>
          </ViewCard>

          <ViewCard title="Claims Analyzer" viewId="claims">
            <p className="text-slate-600 mb-2">
              Slice claims by date, type, cost, and state; see totals and outlier metrics.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>Use for: cost trends, IP/OP/RX mix, high-cost claim review</li>
              <li>Filters: date range, claim type (IP/OP/RX), cost minimum, state</li>
              <li>Metrics: total allowed, PMPM, outlier count (P95), P95 threshold</li>
            </ul>
          </ViewCard>

          <ViewCard title="Risk Adjustment Explorer" viewId="risk">
            <p className="text-slate-600 mb-2">
              Focus on RAF distribution, HCC prevalence, and revenue concentration.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>Use for: where risk revenue is concentrated, which HCCs are most common, RAF bands</li>
              <li>Filters: state, plan type, RAF range, HCC code</li>
              <li>Charts: RAF distribution histogram, HCC prevalence, revenue concentration (e.g. top 10% share)</li>
              <li>Table: members with RAF, suspect count, risk adj. revenue</li>
            </ul>
          </ViewCard>

          <ViewCard title="What-If Simulation" viewId="simulation">
            <p className="text-slate-600 mb-2">
              Model impact of plan mix, risk threshold, and closing suspect HCC gaps.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>Use for: “what if we close 30% of suspect HCCs?” or “what if plan mix shifts?”</li>
              <li>Inputs: risk threshold, plan mix (Bronze/Silver/Gold %), close suspect HCC %, coding improvement %</li>
              <li>Outputs: expected MLR, risk-adjusted MLR, total projected cost, total risk revenue, avg RAF, MLR improvement (bps)</li>
            </ul>
          </ViewCard>

          <ViewCard title="Executive Chat" viewId="chat">
            <p className="text-slate-600 mb-2">
              Natural-language questions over the same data and calculations; answers are evidence-backed narratives.
            </p>
            <ul className="list-disc list-inside text-slate-600 space-y-1">
              <li>Use for: “Why is Texas Bronze leaking RAF?”, “Where are we missing risk adjustment revenue?”, “What if we close 30% of suspect HCCs?”, “Which plans have the worst adjusted MLR?”</li>
              <li>Flow: question → query interpreter → risk/finance/compliance agents → narrative (short answer, evidence, why it matters, recommended action, charts)</li>
              <li>Expand “Show evidence” for bullets and inline charts; use follow-up suggestions for drill-down</li>
            </ul>
          </ViewCard>
        </div>
      </section>

      <p className="text-xs text-slate-500 pt-4 border-t border-slate-200">
        Logic is in <code className="bg-slate-100 px-1 rounded">server/risk-adjustment.js</code>, <code className="bg-slate-100 px-1 rounded">server/risk-adjustment-agent.js</code>, and <code className="bg-slate-100 px-1 rounded">server/chat-orchestrator.js</code>.
        This is demo math only; not real CMS-HCC or compliance advice.
      </p>
    </div>
  );
}

function GlossTerm({
  term,
  id,
  children,
}: {
  term: string;
  id: string;
  children: React.ReactNode;
}) {
  return (
    <div id={id} className="bg-slate-50 rounded-lg p-3 border border-slate-100">
      <h4 className="font-medium text-slate-800 mb-1">{term}</h4>
      <div className="text-slate-600">{children}</div>
    </div>
  );
}

function ViewCard({
  title,
  viewId,
  children,
}: {
  title: string;
  viewId: string;
  children: React.ReactNode;
}) {
  return (
    <div id={viewId} className="bg-white border border-slate-200 rounded-lg p-4 shadow-sm">
      <h4 className="font-medium text-slate-800 mb-2">{title}</h4>
      {children}
    </div>
  );
}
